apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: d1z5dy8dz-dotnet-basic
  janus-idp.io/tekton: d1z5dy8dz-dotnet-basic
  backstage.io/kubernetes-id: d1z5dy8dz-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d1z5dy8dz-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
